export {ProfileRoute} from "./profile/ProfileRoute"
export {CollectionsRoute} from "./collections/CollectionsRoute"
export {NFTSRoute} from "./nfts/NFTSRoute"
export {CategoriesRoute} from "./categories/CategoriesRoute"
export {BestCreatorsSellersRoute} from "./landingPage/bestCreatorsSellers"
export {MostPopularCollectionRoute} from "./landingPage/mostPopularCollections"